name: 🔧 Product Defect Report
description: Report a broken, defective, or quality issue with your Blackhawk Braids product
title: "[DEFECT] "
labels: ["defect", "quality-issue", "needs-review"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Product Defect Report
        
        Thank you for reporting this issue. We take product quality seriously and stand behind our USA-made paracord gear.
        
        **This report will be reviewed by our support team within 1-2 business days.**
        
  - type: input
    id: order-number
    attributes:
      label: Order Number
      description: Your order number or confirmation email reference
      placeholder: "e.g., BHB-12345 or confirmation email date"
    validations:
      required: true
      
  - type: dropdown
    id: product-type
    attributes:
      label: Product Type
      description: What type of product is affected?
      options:
        - Bracelet
        - Keychain
        - Lanyard
        - Belt
        - Dog Collar
        - Dog Leash
        - Other Paracord Gear
    validations:
      required: true
      
  - type: dropdown
    id: time-owned
    attributes:
      label: How long have you had the product?
      description: When did you receive this item?
      options:
        - Less than 1 week
        - 1-2 weeks
        - 2-4 weeks
        - 1-3 months
        - 3-6 months
        - 6+ months
    validations:
      required: true
      
  - type: textarea
    id: issue-description
    attributes:
      label: What happened?
      description: Describe the defect or quality issue in detail
      placeholder: "Example: The bracelet broke after 3 days. The paracord separated at the weave near the buckle during normal wear."
    validations:
      required: true
      
  - type: dropdown
    id: usage
    attributes:
      label: How was the product being used?
      description: What were you doing when it broke or when you noticed the defect?
      options:
        - Normal everyday wear
        - Light activity
        - Outdoor/tactical use
        - Heavy-duty use
        - Just noticed defect (not in use)
        - Came defective out of package
    validations:
      required: true
      
  - type: textarea
    id: photos
    attributes:
      label: Photos of the Defect
      description: |
        Please attach clear photos showing:
        - The damaged/defective area
        - Full view of the product
        - Close-up of the issue
        
        Drag and drop images here or click to upload.
      placeholder: "Attach photos here..."
    validations:
      required: false
      
  - type: textarea
    id: desired-resolution
    attributes:
      label: Desired Resolution
      description: What would you like us to do? (Replacement, refund, exchange, etc.)
      placeholder: "Example: I would like a replacement bracelet in the same color/style."
    validations:
      required: false
      
  - type: checkboxes
    id: contact-consent
    attributes:
      label: Contact Confirmation
      description: Our support team may need to contact you for additional information
      options:
        - label: I understand the support team will review this report and may contact me via email
          required: true
          
  - type: markdown
    attributes:
      value: |
        ---
        
        ### What happens next?
        
        1. ✅ Your report is submitted
        2. 👀 Support team reviews within 1-2 business days
        3. 📧 You'll receive follow-up via email or on this issue
        4. 🔄 We'll work to resolve the issue (replacement, refund, or other resolution)
        
        **Note:** Product defects require human review. We cannot automatically process refunds or replacements, but we stand behind our products and will make it right.
        
        ---
        **Blackhawk Braids** - Premium 550 Paracord Gear, Made in America 🇺🇸
